### ISSUE TITLE
Allowing generation in TDI2

### ISSUE THREAD

**Issue by GarethCabournDavies** [mikekatz04/GPU4GW#10]
We are looking at analysing some TDI2 data, and realised that we can't make the waveforms in that definition.

We've identified [this function](https://github.com/mikekatz04/BBHx/blob/dd4c1f5b5a180ca10e699bd0317238be7480f28b/src/Response.cu#L169) as the one which will need editing.

I am happy to do this, but wanted to check whether there is anything you'd prefer me to try and avoid doing before I start, that would be great!

**Comment by mikekatz04** [comment]
Hi Gareth, sorry for the long delay. Did you end up doing this?

**Comment by GarethCabournDavies** [comment]
I haven't added this yet, as we have decided that the work we're doing will be okay with TDI1

**Comment by mikekatz04** [comment]
This has been added to the response function in the Equal Armlength limit in version >=1.1.0.
