### ISSUE TITLE
Add lapacke linking in setup.py

### ISSUE THREAD

**Issue by rjrosati** [mikekatz04/GPU4GW#11]
This is basically the same issue as https://github.com/BlackHolePerturbationToolkit/FastEMRIWaveforms/issues/8 , and fails to link to lapacke correctly whenever you're not in a conda environment.

It's an easy fix, just adding lapacke to the right lines in setup.py. PR incoming shortly

**Comment by mikekatz04** [comment]
Closed with pull request
