### ISSUE TITLE
Not pip installable yet

### ISSUE THREAD

**Issue by snwnde** [mikekatz04/GPU4GW#13]
This commit https://github.com/mikekatz04/BBHx/commit/01c54a579a0dd55234fea1a1bebdb966fe9e0b6c moves some copy scripts into `scripts/prebuild.py` but they are somehow not run during the building despite the declaration in `MANIFEST.in`. As such, the installer complains
```python
 ValueError: 'src/phenomhm_cpu.pyx' doesn't match any files
 ```

**Comment by mikekatz04** [comment]
If installing from source, run `scripts/prebuild.py` before installing. It is now pip installable from pypi. If this remains and issue, reopen it.
