### ISSUE TITLE
Is the output of LISA response function normalized? 

### ISSUE THREAD

**Issue by DrizzleatDusk** [mikekatz04/GPU4GW#14]
I have read the [example notebook](https://github.com/mikekatz04/BBHx/blob/master/examples/bbhx_tutorial.ipynb) and got confused with the unit of detector response. For example, y label in Out [4].

As shown in that figure, the unit of strain data is $\mathrm{Hz}^{-1/2}$. This means that the amplitude is normalized as $|\tilde{h}(f)|\sqrt{f}$. But, I do not think this normalization is adpoted here. Then, I agree the quantity represented by y-axis is $|\tilde{h}|$. 

However, the LISA response is represented by fractional frequency shift and its unit is 1. Then, the unit of its Fourier transform should be $\mathrm{Hz}^{-1}$ since it is calculated within an integral in time domain. Therefore, I suspect there is a typo in the label.

Maybe I have some misunderstandings. I would thank your explanations greatly if you can let me know.

**Comment by mikekatz04** [comment]
The strain data I believe is in fractional frequency (unitless) in the time-domain. Transformed, we apply a factor of `sqrt(dt)` (1/Hz^(1/2)) to properly match units for the inner product. I believe that is what is plotted.
