### ISSUE TITLE
Mode order in documentation plots

### ISSUE THREAD

**Issue by mj-will** [mikekatz04/GPU4GW#15]
In [this section](https://mikekatz04.github.io/BBHx/html/bbhx_tutorial.html#Generating-PhenomHM-waveforms) of the documentation, the mode-by-mode amplitude produced by `PhenomHMAmpPhase` is plotted but the `modes` argument for `PhenomHMAmpPhase` is not specified. Looking at the code, I don't think the default order matches what is used in the tutorial (https://github.com/mikekatz04/BBHx/blob/master/bbhx/waveforms/phenomhm.py#L122), so I think the labels are incorrect in the plot.

**Comment by mikekatz04** [comment]
This is fixed. Thank you for pointing this out!
